name: advent_of_code_2023
description: Tek's repo for Advent of Code 2023
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
